/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.todo;

import org.junit.jupiter.api.Test;

import com.todo.Todo;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        Todo classUnderTest = new Todo();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
